# Generated by Django 4.2 on 2023-04-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suduko', '0002_alter_leaderboardentry_player_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaderboardEntry',
        ),
    ]
